// ==========================================
// TRANSLATION DATA FILE — Edit once to update both versions
// ==========================================

export const translations = {
  ar: {
    siteConfig: {
      name: "AdVision",
      tagline: "وكالة الإبداع والتأثير",
      description: "نبتكر حلولاً إعلانية مدروسة تربط علامتك التجارية بجمهورك المستهدف وتحقق نتائج قابلة للقياس.",
      email: "hello@advision.agency",
      phone: "+966 50 000 0000",
      address: "الرياض، المملكة العربية السعودية",
      workingHours: "الأحد – الخميس، ٩ص – ٦م",
      socialLinks: {
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
        youtube: "https://youtube.com",
      },
    },
    navLinks: [
      { href: "/", label: "الرئيسية" },
      { href: "/services", label: "خدماتنا" },
      { href: "/portfolio", label: "أعمالنا" },
      { href: "/blog", label: "المدونة" },
      { href: "/about", label: "من نحن" },
      { href: "/contact", label: "تواصل معنا" },
    ],
    common: {
      dashboardBtn: "لوحة التحكم",
      readMore: "اقرأ المزيد",
      requestService: "اطلب الخدمة",
      contactUs: "تواصل معنا",
      contactUsNow: "تواصل معنا الآن",
      exploreServices: "استكشف الخدمات",
      allServices: "جميع الخدمات بالتفصيل",
      successTitle: "تم الإرسال بنجاح!",
      successDesc: "وصلتنا رسالتك وسيتواصل معك فريقنا خلال ٢٤ ساعة.",
      sendAnother: "إرسال رسالة أخرى",
      loading: "⏳ جارٍ الإرسال...",
      submitBtn: "إرسال الرسالة",
      whyUs: "لماذا AdVision؟",
    },
    heroData: {
      badge: "✦ وكالة الإبداع والتأثير",
      headline1: "نصنع الإعلانات التي",
      headline2: "تُحرّك العالم",
      subtext: "نبتكر حلولاً إعلانية مدروسة تربط علامتك التجارية بجمهورك المستهدف وتحقق نتائج قابلة للقياس.",
      cta1: { label: "ابدأ معنا الآن ←", href: "/contact" },
      cta2: { label: "استكشف خدماتنا", href: "/services" },
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop",
      imageAlt: "فريق وكالة إعلانية مبتكر",
      badges: ["شريك جوجل ✓", "شريك ميتا ✓", "معتمد ISO ✓"],
    },
    homeData: {
      servicesTitle: "كل ما تحتاجه لعلامتك التجارية",
      servicesSubtext: "نقدم حلولاً شاملة تغطي كل جوانب التسويق الرقمي والإعلان",
      ctaBannerTitle: "جاهز تبدأ رحلتك معنا؟",
      ctaBannerText: "تواصل معنا اليوم واحصل على استشارة مجانية لتطوير استراتيجيتك التسويقية",
    },
    statsData: [
      { value: "٢٥٠+", label: "عميل راضٍ", icon: "🤝" },
      { value: "١٢٠٠+", label: "حملة ناجحة", icon: "🎯" },
      { value: "٩٨٪", label: "رضا العملاء", icon: "⭐" },
      { value: "١٠+", label: "سنوات خبرة", icon: "🏆" },
    ],
    servicesData: [
      {
        id: "digital-ads",
        icon: "🎯",
        title: "الإعلان الرقمي",
        shortDesc: "حملات إعلانية مستهدفة على جميع المنصات الرقمية بأعلى معدلات التحويل.",
        price: "يبدأ من ٢٠٠٠ ريال/شهر",
        fullDesc: "نصمم وندير حملات إعلانية متكاملة على Google Ads وMeta Ads وSnapchat وTikTok. نستهدف جمهورك المثالي بدقة عالية ونحسّن الحملات باستمرار لأعلى عائد على الاستثمار.",
        features: ["تحليل الجمهور المستهدف", "إعداد وإطلاق الحملات", "تقارير أسبوعية", "تحسين مستمر للأداء"],
      },
      {
        id: "identity",
        icon: "🎨",
        title: "تصميم الهوية البصرية",
        shortDesc: "تصميم هوية تجارية متكاملة تعكس قيم علامتك التجارية وتميزك.",
        price: "يبدأ من ٥٠٠٠ ريال",
        fullDesc: "نبني هوية بصرية قوية ومتماسكة تشمل الشعار والألوان والخطوط وجميع التطبيقات. هوية تروي قصتك وتثير مشاعر جمهورك.",
        features: ["تصميم الشعار", "دليل الهوية البصرية", "تصاميم مطبوعات", "ملفات بصيغ متعددة"],
      },
      {
        id: "social",
        icon: "📱",
        title: "إدارة السوشيال ميديا",
        shortDesc: "إدارة احترافية لحساباتك مع محتوى يومي مبتكر وتفاعل حقيقي.",
        price: "يبدأ من ٣٠٠٠ ريال/شهر",
        fullDesc: "ندير حساباتك على Instagram وX وTikTok وLinkedIn بمحتوى إبداعي يجذب الجمهور ويبني مجتمعاً حقيقياً حول علامتك.",
        features: ["١٥ منشور شهرياً", "تصميم المحتوى", "الرد على التعليقات", "تقرير شهري"],
      },
      {
        id: "video",
        icon: "🎬",
        title: "إنتاج المحتوى المرئي",
        shortDesc: "فيديوهات إعلانية ورؤيوية احترافية تحكي قصة علامتك بأسلوب مؤثر.",
        price: "يبدأ من ٤٠٠٠ ريال",
        fullDesc: "من الفكرة إلى الشاشة — نكتب السيناريو ونصمم الموشن والتصوير والمونتاج الاحترافي لإنتاج محتوى مرئي يبقى في الذاكرة.",
        features: ["سيناريو إبداعي", "تصوير احترافي", "مونتاج وتأثيرات", "نسخ متعددة للمنصات"],
      },
      {
        id: "seo",
        icon: "🔍",
        title: "تحسين محركات البحث SEO",
        shortDesc: "ارتقِ بترتيب موقعك في Google واجذب زوار مستهدفين.",
        price: "يبدأ من ٢٥٠٠ ريال/شهر",
        fullDesc: "نحسّن موقعك من الداخل والخارج — من تحليل الكلمات المفتاحية وبناء الروابط وتحسين الكود وحتى المحتوى — لرفع ترتيبك في نتائج البحث.",
        features: ["تحليل الكلمات المفتاحية", "تحسين داخل الموقع", "بناء الروابط الخارجية", "تقرير تحسين شهري"],
      },
      {
        id: "strategy",
        icon: "📊",
        title: "التحليل والاستراتيجية",
        shortDesc: "دراسة معمّقة لسوقك ومنافسيك وإعداد استراتيجية تسويقية متكاملة.",
        price: "يبدأ من ٣٥٠٠ ريال",
        fullDesc: "نحلل سوقك ومنافسيك وجمهورك ثم نضع خارطة طريق تسويقية مبنية على بيانات حقيقية، لتتخذ قرارات أذكى وتنمو أسرع.",
        features: ["تحليل المنافسين", "دراسة السوق", "خارطة الطريق التسويقية", "جلسة استشارية شاملة"],
      },
    ],
    processData: {
      badge: "كيف نعمل",
      title: "رحلتك معنا خطوة بخطوة",
      steps: [
        { step: "١", title: "الاستشارة المجانية", desc: "نتعرف على مشروعك وأهدافك وتحدياتك في جلسة مفتوحة." },
        { step: "٢", title: "التحليل والدراسة", desc: "ندرس سوقك ومنافسيك ونضع الاستراتيجية المثلى." },
        { step: "٣", title: "التنفيذ الإبداعي", desc: "فريقنا يبدأ العمل بأعلى معايير الجودة والإبداع." },
        { step: "٤", title: "المتابعة والتحسين", desc: "نراقب النتائج ونحسّن الأداء باستمرار لضمان أفضل النتائج." },
      ]
    },
    testimonialsData: {
      badge: "آراء عملائنا",
      title: "ماذا قالوا عنّا",
      list: [
        {
          name: "أحمد الشمري",
          role: "مدير تسويق، شركة النخبة",
          text: "AdVision غيّرت طريقة تفكيرنا في التسويق الرقمي. النتائج تجاوزت توقعاتنا بكثير.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "سارة القحطاني",
          role: "رائدة أعمال",
          text: "تعاملت مع وكالات كثيرة لكن AdVision الأكثر احترافية والأسرع في التنفيذ. أنصح بها بشدة.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "محمد العتيبي",
          role: "مؤسس، براند ماكس",
          text: "زادت مبيعاتنا ٣٠٠٪ خلال ٦ أشهر من العمل مع AdVision. فريق رائع!",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "لطيفة الدوسري",
          role: "مديرة تنفيذية، ريادة",
          text: "الاحترافية والإبداع في كل تفصيلة. لن أتعامل مع أي وكالة أخرى بعد الآن.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
        },
      ]
    },
    faqData: {
      badge: "الأسئلة الشائعة",
      title: "أجوبة لأهم أسئلتك",
      list: [
        { q: "كم يستغرق تنفيذ الهوية البصرية؟", a: "عادةً ١٠–١٤ يوم عمل، تشمل مراحل البحث والتصميم والمراجعات." },
        { q: "هل تعملون مع الشركات الصغيرة؟", a: "نعم، لدينا باقات مناسبة لكل الأحجام من الفرد حتى الشركة الكبيرة." },
        { q: "كيف يتم الدفع؟", a: "نقبل الدفع بالتحويل البنكي أو المدى أو الفيزا. عادةً ٥٠٪ مقدم و٥٠٪ عند التسليم." },
        { q: "هل تقدمون تقارير للحملات؟", a: "بالطبع، تقارير أسبوعية وشهرية مفصّلة مع جميع المؤشرات الرئيسية." },
        { q: "هل يمكنني تعديل الباقة لاحقاً؟", a: "نعم، باقاتنا مرنة ويمكن تعديلها في أي وقت حسب احتياجاتك." },
      ]
    },
    aboutData: {
      badge: "من نحن",
      title: "قصتنا تبدأ بشغف الإبداع",
      subtext: "تأسست AdVision عام ٢٠١٤ بحلم بسيط: نساعد كل علامة تجارية أن تُرى، تُسمع، وتُحبّ.",
      storyBadge: "قصتنا",
      storyTitle: "نبنى النجاح مع عملائنا، واحداً تلو الآخر",
      storyDesc1: "منذ تأسيسنا، عملنا مع أكثر من ٢٥٠ عميل في قطاعات متنوعة — من الشركات الناشئة حتى المؤسسات الكبرى.",
      storyDesc2: "نؤمن بأن كل علامة تجارية تحمل قصة فريدة، ومهمتنا هي إيصال تلك القصة بأقوى وأجمل صورة ممكنة.",
      storyCta: "تحدث معنا",
      storyImage: "https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?q=80&w=800&auto=format&fit=crop",
      missionTitle: "مهمتنا",
      missionDesc: "مساعدة الشركات والعلامات التجارية في العالم العربي على النمو الرقمي من خلال حلول إعلانية مبتكرة ومدروسة تحقق نتائج ملموسة وقابلة للقياس.",
      visionTitle: "رؤيتنا",
      visionDesc: "أن نكون الوكالة الإعلانية الرائدة في المنطقة العربية، المعروفة بالإبداع والكفاءة والنتائج الاستثنائية التي تتجاوز توقعات عملائنا.",
      valuesBadge: "قيمنا",
      valuesTitle: "ما الذي يجعلنا مختلفين",
      valuesList: [
        { icon: "💡", title: "الإبداع", desc: "نؤمن أن أفضل الحلول تولد من خارج الصندوق." },
        { icon: "🎯", title: "الدقة", desc: "كل قرار مبني على بيانات وتحليل دقيق." },
        { icon: "🤝", title: "الشراكة", desc: "نجاحك هو نجاحنا — نعمل كفريق واحد." },
        { icon: "⚡", title: "السرعة", desc: "نلتزم بالمواعيد ونسلّم بجودة لا تتنازل." },
      ],
      teamBadge: "فريقنا",
      teamTitle: "العقول المبدعة خلف النجاح",
      teamList: [
        { name: "خالد المنصور", role: "المدير التنفيذي", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop", bio: "١٥ سنة خبرة في عالم التسويق والإعلان الرقمي." },
        { name: "نورة العمري", role: "مديرة الإبداع", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop", bio: "مصممة جرافيك حائزة على جوائز دولية متعددة." },
        { name: "فيصل الدوسري", role: "مدير الحملات الرقمية", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop", bio: "متخصص في إعلانات Google وMeta بخبرة ١٠ سنوات." },
        { name: "ريم السالم", role: "مديرة المحتوى", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop", bio: "كاتبة ومستراتيجية محتوى بخلفية إعلامية قوية." },
      ],
      partnersBadge: "شركاؤنا وشهاداتنا",
    },
    servicesPage: {
      badge: "خدماتنا",
      title: "حلول إعلانية لكل احتياج",
      subtext: "من التصميم إلى الحملات الرقمية، نقدم خدمات متكاملة ترتقي بعلامتك التجارية",
      whyTitle: "لماذا AdVision؟",
      whyList: [
        { icon: "🎯", title: "نتائج مضمونة", desc: "نعمل على أساس الأهداف ونتحمل مسؤولية النتائج." },
        { icon: "📊", title: "شفافية كاملة", desc: "تقارير تفصيلية ومفهومة لكل ريال تنفقه." },
        { icon: "⚡", title: "تنفيذ سريع", desc: "لا تأخير، نلتزم بالمواعيد في كل مشروع." },
        { icon: "🤝", title: "دعم مستمر", desc: "فريقنا متاح دائماً للإجابة على استفساراتك." },
      ],
      ctaTitle: "مستعد تبدأ معنا؟",
      ctaSub: "استشارة مجانية في انتظارك",
      ctaBtn: "تواصل معنا الآن ←",
    },
    contactPage: {
      badge: "تواصل معنا",
      title: "نحن هنا لمساعدتك",
      subtext: "أرسل لنا رسالة وسيتواصل معك أحد خبرائنا في أقرب وقت ممكن",
      infoTitle: "معلومات الاتصال",
      infoList: [
        { icon: "📧", label: "البريد الإلكتروني", value: "hello@advision.agency" },
        { icon: "📞", label: "الهاتف", value: "+966 50 000 0000" },
        { icon: "📍", label: "العنوان", value: "الرياض، المملكة العربية السعودية" },
        { icon: "⏰", label: "ساعات العمل", value: "الأحد – الخميس، ٩ص – ٦م" },
      ],
      formTitle: "أرسل رسالة",
      labels: {
        name: "الاسم الكامل *",
        email: "البريد الإلكتروني *",
        phone: "رقم الهاتف",
        service: "الخدمة المطلوبة",
        message: "رسالتك *",
        chooseService: "اختر الخدمة",
      },
      placeholders: {
        name: "أحمد محمد",
        email: "ahmed@example.com",
        phone: "+966 5X XXX XXXX",
        message: "أخبرنا عن مشروعك وما تحتاجه...",
      }
    },
    blogPage: {
      badge: "المدونة",
      title: "آخر الأخبار والرؤى التسويقية",
      subtext: "تابع أحدث المقالات والإلهامات حول الإعلان الرقمي، التسويق، والهوية البصرية.",
      posts: [
        {
          id: "post-1",
          title: "كيف ترفع عائد الاستثمار من حملاتك الرقمية",
          excerpt: "أسرار اختيار الجمهور الصحيح، صياغة الرسالة الأمثل، وتحليل الأرقام لتحسين الأداء.",
          date: "٢٠ يونيو ٢٠٢٦",
          category: "إعلان رقمي",
        },
        {
          id: "post-2",
          title: "أهم ٥ اتجاهات في تصميم الهوية البصرية لعام ٢٠٢٦",
          excerpt: "اكتشف ملامح التصميم التي تساعد علامتك التجارية على البروز في السوق.",
          date: "١٥ يونيو ٢٠٢٦",
          category: "تصميم",
        },
        {
          id: "post-3",
          title: "طرق مبتكرة لبناء استراتيجية محتوى فعّالة",
          excerpt: "من الفكرة إلى التوزيع — كيف تصنع محتوى يجذب العملاء ويحتفظ بهم.",
          date: "١٠ يونيو ٢٠٢٦",
          category: "محتوى",
        }
      ]
    },
    footer: {
      brandDesc: "وكالتك الإعلانية الأولى في العالم العربي. نبتكر، نصمم، ونوصل رسالتك بأقوى تأثير.",
      quickLinks: "روابط سريعة",
      contactUs: "تواصل معنا",
      allRights: "جميع الحقوق محفوظة.",
      adminDashboard: "لوحة تحكم الإدارة ←",
    },
    announcementBar: "🎉 عرض خاص: استشارة تسويقية مجانية لأول ١٠ عملاء هذا الشهر!",
    showAnnouncementBar: true
  },
  en: {
    siteConfig: {
      name: "AdVision",
      tagline: "The Agency of Creativity & Impact",
      description: "We craft strategic advertising solutions that connect your brand with your target audience and deliver measurable results.",
      email: "hello@advision.agency",
      phone: "+966 50 000 0000",
      address: "Riyadh, Saudi Arabia",
      workingHours: "Sunday – Thursday, 9AM – 6PM",
      socialLinks: {
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
        youtube: "https://youtube.com",
      },
    },
    navLinks: [
      { href: "/", label: "Home" },
      { href: "/services", label: "Services" },
      { href: "/portfolio", label: "Portfolio" },
      { href: "/blog", label: "Blog" },
      { href: "/about", label: "About Us" },
      { href: "/contact", label: "Contact Us" },
    ],
    common: {
      dashboardBtn: "Dashboard",
      readMore: "Read More",
      requestService: "Request Service",
      contactUs: "Contact Us",
      contactUsNow: "Contact Us Now",
      exploreServices: "Explore Services",
      allServices: "All Services in Detail",
      successTitle: "Sent Successfully!",
      successDesc: "We have received your message and our team will get in touch within 24 hours.",
      sendAnother: "Send Another Message",
      loading: "⏳ Sending...",
      submitBtn: "Send Message",
      whyUs: "Why AdVision?",
    },
    heroData: {
      badge: "✦ Creativity & Impact Agency",
      headline1: "We Make Ads That",
      headline2: "Move the World",
      subtext: "We craft strategic advertising solutions that connect your brand with your target audience and deliver measurable results.",
      cta1: { label: "Start With Us Now →", href: "/contact" },
      cta2: { label: "Explore Our Services", href: "/services" },
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop",
      imageAlt: "Creative agency workspace and team brainstorming",
      badges: ["Google Partner ✓", "Meta Business ✓", "ISO Certified ✓"],
    },
    homeData: {
      servicesTitle: "Everything You Need for Your Brand",
      servicesSubtext: "We provide holistic marketing solutions designed to drive scalable growth.",
      ctaBannerTitle: "Ready to Start Your Journey?",
      ctaBannerText: "Get in touch today and receive a free campaign consultation to accelerate growth.",
    },
    statsData: [
      { value: "250+", label: "Happy Clients", icon: "🤝" },
      { value: "1200+", label: "Successful Campaigns", icon: "🎯" },
      { value: "98%", label: "Client Satisfaction", icon: "⭐" },
      { value: "10+", label: "Years of Experience", icon: "🏆" },
    ],
    servicesData: [
      {
        id: "digital-ads",
        icon: "🎯",
        title: "Digital Advertising",
        shortDesc: "Targeted advertising campaigns across all digital platforms with high conversion rates.",
        price: "Starts from 2,000 SAR/month",
        fullDesc: "We design and manage comprehensive ad campaigns on Google Ads, Meta Ads, Snapchat, and TikTok. We precisely target your ideal audience and continuously optimize for the highest return on investment.",
        features: ["Target Audience Analysis", "Campaign Setup & Launch", "Weekly Performance Reports", "Continuous Optimization"],
      },
      {
        id: "identity",
        icon: "🎨",
        title: "Brand Identity Design",
        shortDesc: "Complete brand identity designs reflecting your values and setting you apart.",
        price: "Starts from 5,000 SAR",
        fullDesc: "We build strong and cohesive visual identities including logos, color palettes, typography, and stationery. An identity that tells your story and connects emotionally with your audience.",
        features: ["Custom Logo Design", "Brand Guidelines Manual", "Print & Stationery Designs", "Multi-format Source Files"],
      },
      {
        id: "social",
        icon: "📱",
        title: "Social Media Management",
        shortDesc: "Professional account management with daily creative content and organic growth.",
        price: "Starts from 3,000 SAR/month",
        fullDesc: "We manage your accounts on Instagram, X, TikTok, and LinkedIn with creative content that engages the audience and builds a loyal community around your brand.",
        features: ["15 Custom Posts Monthly", "Content Design & Writing", "Comment & Message Moderation", "Monthly Insights Report"],
      },
      {
        id: "video",
        icon: "🎬",
        title: "Visual Content Production",
        shortDesc: "Professional promotional and story-driven videos that communicate with style.",
        price: "Starts from 4,000 SAR",
        fullDesc: "From concept to screen — we write scripts, design motion graphics, direct filming, and do professional editing to produce visual content that leaves a lasting impression.",
        features: ["Creative Scriptwriting", "Professional Video Shoots", "Editing & Post-production", "Optimized Video Formats"],
      },
      {
        id: "seo",
        icon: "🔍",
        title: "Search Engine Optimization",
        shortDesc: "Boost your Google rankings and attract organic, high-intent traffic.",
        price: "Starts from 2,500 SAR/month",
        fullDesc: "We optimize your website from the inside out — covering keyword research, link building, code optimization, and SEO content writing to improve your rankings on search engines.",
        features: ["Keyword Research & Strategy", "On-Page SEO Optimization", "High-Quality Backlinking", "Monthly Ranking Reports"],
      },
      {
        id: "strategy",
        icon: "📊",
        title: "Analysis & Marketing Strategy",
        shortDesc: "In-depth market and competitor research to draft a robust marketing strategy.",
        price: "Starts from 3,500 SAR",
        fullDesc: "We analyze your market, competitors, and audience, then formulate a data-driven marketing roadmap to help you make smarter decisions and grow faster.",
        features: ["Competitor Analysis", "Market Research Study", "Marketing Roadmap Blueprint", "Consultation Strategy Session"],
      },
    ],
    processData: {
      badge: "How We Work",
      title: "Your Journey With Us Step-by-Step",
      steps: [
        { step: "1", title: "Free Consultation", desc: "We discuss your project, goals, and challenges in an open strategy session." },
        { step: "2", title: "Analysis & Strategy", desc: "We study your market and competitors to outline the optimal campaign plan." },
        { step: "3", title: "Creative Execution", desc: "Our creative team begins crafting the assets to the highest industry standards." },
        { step: "4", title: "Monitoring & Optimization", desc: "We track performance metrics and optimize campaigns for maximum return." },
      ]
    },
    testimonialsData: {
      badge: "Client Testimonials",
      title: "What They Say About Us",
      list: [
        {
          name: "Ahmed Al-Shammari",
          role: "Marketing Director, Al-Nokhba Co.",
          text: "AdVision changed the way we think about digital marketing. The results surpassed our expectations.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "Sara Al-Qahtani",
          role: "Entrepreneur",
          text: "I have worked with many agencies, but AdVision is by far the most professional and prompt. Strongly recommended.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "Mohamed Al-Otaibi",
          role: "Founder, BrandMax",
          text: "Our sales increased by 300% within 6 months of working with AdVision. A phenomenal team!",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "Latifa Al-Dousari",
          role: "CEO, Reyadah Group",
          text: "Professionalism and creativity in every tiny detail. I will never work with any other agency again.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
        },
      ]
    },
    faqData: {
      badge: "FAQ",
      title: "Answers to Your Key Questions",
      list: [
        { q: "How long does a brand identity take?", a: "Typically 10-14 business days, including research, design drafts, and revisions." },
        { q: "Do you work with small businesses?", a: "Yes, we have tailored packages designed for setups of all sizes, from startups to corporates." },
        { q: "What are the payment terms?", a: "We accept bank transfers and major cards. Terms are usually 50% upfront and 50% upon delivery." },
        { q: "Do you provide campaign reports?", a: "Absolutely. We supply detailed weekly and monthly reports tracking all major key performance indicators (KPIs)." },
        { q: "Can I upgrade or downgrade my plan later?", a: "Yes, our plans are flexible and can be adapted at any time according to your business needs." },
      ]
    },
    aboutData: {
      badge: "About Us",
      title: "Our Story Begins with a Passion for Creativity",
      subtext: "Founded in 2014, AdVision was built on a simple dream: to help every brand be seen, heard, and loved.",
      storyBadge: "Our Story",
      storyTitle: "Building Success with Our Clients, One by One",
      storyDesc1: "Since our launch, we have partnered with over 250 clients across various sectors — ranging from hot startups to large enterprises.",
      storyDesc2: "We believe every brand carries a unique story, and our mission is to communicate that story in the most powerful and beautiful way possible.",
      storyCta: "Talk to Us",
      storyImage: "https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?q=80&w=800&auto=format&fit=crop",
      missionTitle: "Our Mission",
      missionDesc: "Empowering businesses and brands in the Arab world to grow digitally by offering clever, data-backed advertising solutions that yield tangible, measurable success.",
      visionTitle: "Our Vision",
      visionDesc: "To be the leading advertising agency in the Arab region, recognized for creativity, efficiency, and delivering exceptional outcomes that exceed client expectations.",
      valuesBadge: "Our Values",
      valuesTitle: "What Sets Us Apart",
      valuesList: [
        { icon: "💡", title: "Creativity", desc: "We believe the best solutions are born thinking outside the box." },
        { icon: "🎯", title: "Precision", desc: "Every campaign decision is supported by analytics and solid data." },
        { icon: "🤝", title: "Partnership", desc: "Your success is our success — we operate as a unified team." },
        { icon: "⚡", title: "Velocity", desc: "We respect deadlines and deliver quality without compromises." },
      ],
      teamBadge: "Our Team",
      teamTitle: "The Creative Minds Behind Our Success",
      teamList: [
        { name: "Khaled Al-Mansour", role: "Chief Executive Officer", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop", bio: "15 years of leadership experience in digital marketing and advertising." },
        { name: "Noura Al-Omari", role: "Creative Director", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop", bio: "An award-winning graphic designer with an international design background." },
        { name: "Faisal Al-Dousari", role: "Digital Campaigns Director", image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop", bio: "Google & Meta ads certified specialist with 10+ years optimizing digital ad spend." },
        { name: "Reem Al-Salem", role: "Content Strategy Manager", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop", bio: "Copywriter and content strategist with a strong background in media relations." },
      ],
      partnersBadge: "Our Partners & Certifications",
    },
    servicesPage: {
      badge: "Our Services",
      title: "Advertising Solutions Tailored for Every Need",
      subtext: "From creative designs to high-performance campaigns, we deliver end-to-end services to scale your brand.",
      whyTitle: "Why Choose AdVision?",
      whyList: [
        { icon: "🎯", title: "Guaranteed Results", desc: "We focus on key outcomes and stand accountable for campaign performance." },
        { icon: "📊", title: "Total Transparency", desc: "Understand exactly where your marketing spend goes with easy, detailed reports." },
        { icon: "⚡", title: "Fast Turnaround", desc: "We strictly stick to project milestones and guarantee zero delay." },
        { icon: "🤝", title: "Constant Support", desc: "Our professional support staff is always online to help with requests." },
      ],
      ctaTitle: "Ready to Start Your Journey?",
      ctaSub: "A free strategic consultation is waiting for you.",
      ctaBtn: "Contact Us Now ←",
    },
    contactPage: {
      badge: "Contact Us",
      title: "We Are Here to Help",
      subtext: "Send us a message and one of our experts will get in touch shortly.",
      infoTitle: "Contact Info",
      infoList: [
        { icon: "📧", label: "Email Address", value: "hello@advision.agency" },
        { icon: "📞", label: "Phone Number", value: "+966 50 000 0000" },
        { icon: "📍", label: "Office Address", value: "Riyadh, Kingdom of Saudi Arabia" },
        { icon: "⏰", label: "Working Hours", value: "Sunday – Thursday, 9AM – 6PM" },
      ],
      formTitle: "Send a Message",
      labels: {
        name: "Full Name *",
        email: "Email Address *",
        phone: "Phone Number",
        service: "Requested Service",
        message: "Your Message *",
        chooseService: "Choose a Service",
      },
      placeholders: {
        name: "John Doe",
        email: "john@example.com",
        phone: "+966 5X XXX XXXX",
        message: "Tell us about your project requirements and goals...",
      }
    },
    blogPage: {
      badge: "Blog",
      title: "Latest News & Marketing Insights",
      subtext: "Stay updated with our latest articles on digital advertising, branding, and creative strategy.",
      posts: [
        {
          id: "post-1",
          title: "How to Boost ROI from Your Digital Campaigns",
          excerpt: "Discover the secrets of audience targeting, message crafting, and analytics optimization.",
          date: "June 20, 2026",
          category: "Digital Ads",
        },
        {
          id: "post-2",
          title: "Top 5 Brand Identity Trends for 2026",
          excerpt: "Learn the design cues that will help your brand stand out in a competitive market.",
          date: "June 15, 2026",
          category: "Design",
        },
        {
          id: "post-3",
          title: "Creative Content Strategy Techniques That Work",
          excerpt: "From idea to distribution — how to build content that attracts and retains customers.",
          date: "June 10, 2026",
          category: "Content",
        }
      ]
    },
    footer: {
      brandDesc: "Your premier advertising agency in the Arab world. We innovate, design, and deliver your messages with peak impact.",
      quickLinks: "Quick Links",
      contactUs: "Contact Us",
      allRights: "All rights reserved.",
      adminDashboard: "Admin Dashboard →",
    },
    announcementBar: "🎉 Special Offer: Free marketing consultation for the first 10 clients this month!",
    showAnnouncementBar: true
  }
};

export type Locale = keyof typeof translations;
export type Translation = typeof translations.ar;
export type ServiceDataItem = typeof translations.ar.servicesData[number];
export type StatDataItem = typeof translations.ar.statsData[number];
export type ProcessStep = typeof translations.ar.processData.steps[number];
export type TestimonialItem = typeof translations.ar.testimonialsData.list[number];
export type WhyListItem = typeof translations.ar.servicesPage.whyList[number];
export type InfoItem = typeof translations.ar.contactPage.infoList[number];
export type FaqItem = typeof translations.ar.faqData.list[number];
export type TeamMember = typeof translations.ar.aboutData.teamList[number];
export type ValueItem = typeof translations.ar.aboutData.valuesList[number];

